## MERGE TIAP DIREKTORI

In [1]:
import os
import json
import pandas as pd
import csv

# Langsung arahkan ke folder 'eng'
BASE_DIR = r"C:\Users\Liza\Documents\Kerja Praktik 2\dataset\eng"

data = []
total_files = 0
total_items = 0

print(f"📂 Memulai proses di folder: {BASE_DIR}")

if not os.path.exists(BASE_DIR):
    print("❌ Folder tidak ditemukan!")
else:
    for root, dirs, files in os.walk(BASE_DIR):
        for filename in files:
            if not filename.lower().endswith(".json"):
                continue

            file_path = os.path.join(root, filename)
            print(f"📄 Processing: {filename}")
            
            total_files += 1

            # ===== PARSE NAMA FILE =====
            # 1. Ambil nama lengkap tanpa .json untuk kolom source
            source_full_name = filename.replace(".json", "")
            
            # 2. Tetap split untuk menentukan 'generate_from'
            parts = source_full_name.split("_")
            if len(parts) >= 2:
                generate_from = parts[1]
                if generate_from.upper() != "GPT":
                    generate_from = "GROK"
            else:
                generate_from = "UNKNOWN"

            # ===== LOAD JSON =====
            try:
                with open(file_path, "r", encoding="utf-8") as f:
                    content = json.load(f)

                if isinstance(content, dict):
                    content = content.get("data", [])

                if not isinstance(content, list):
                    continue

                added_count = 0
                for item in content:
                    question = item.get("Question") or item.get("question") or ""
                    answer = item.get("Answer") or item.get("answer") or ""

                    if question.strip() == "" or answer.strip() == "":
                        continue

                    data.append({
                        "question": question.strip(),
                        "answer": answer.strip(),
                        "from": generate_from,
                        "source": source_full_name, # Sekarang berisi nama file lengkap (minus .json)
                        "folder": "eng"
                    })
                    added_count += 1

                total_items += added_count
                print(f"    ✅ Ditambahkan: {added_count}")

            except Exception as e:
                print(f"  ❌ ERROR pada file {filename}: {e}")

# ===== SAVE =====
df = pd.DataFrame(data)

if df.empty:
    print("\n⚠️ Data kosong!")
else:
    # 1. Tampilkan duplikat untuk pengecekan
    duplicates = df[df.duplicated(subset=["question", "answer"], keep=False)]
    if not duplicates.empty:
        print(f"\n🔍 Ditemukan {len(duplicates)} baris duplikat. Detail di: cek_duplikat_eng.csv")
        duplicates.sort_values("question").to_csv("cek_duplikat_eng.csv", index=False, sep=";")

    # 2. Bersihkan duplikat
    df_clean = df.drop_duplicates(subset=["question", "answer"])
    
    output_name = "combined_dataset_eng.csv"
    df_clean.to_csv(
        output_name,
        index=False,
        encoding="utf-8",
        sep=";",
        quoting=csv.QUOTE_ALL
    )

    print("\n" + "="*30)
    print("📊 SUMMARY (FOLDER ENG)")
    print(f"Total file JSON diproses       : {total_files}")
    print(f"Total data mentah              : {total_items}")
    print(f"Total data unik (final)        : {len(df_clean)}")
    print(f"File final disimpan di         : {output_name}")
    print("="*30)

📂 Memulai proses di folder: C:\Users\Liza\Documents\Kerja Praktik 2\dataset\eng
📄 Processing: D1_GPT_HealthPsycology152-167_50.json
    ✅ Ditambahkan: 50
📄 Processing: D1_GPT_HealthPsycology168-183_30.json
    ✅ Ditambahkan: 30
📄 Processing: D1_GPT_HealthPsycology184-208_50.json
    ✅ Ditambahkan: 50
📄 Processing: D1_GPT_HealthPsycology209-229_49.json
    ✅ Ditambahkan: 49
📄 Processing: D1_GPT_HealthPsycology250-268_53.json
    ✅ Ditambahkan: 53
📄 Processing: D1_GROK_HealthPsycology1-55_67.json
    ✅ Ditambahkan: 67
📄 Processing: D1_GROK_HealthPsycology114-151_58.json
    ✅ Ditambahkan: 58
📄 Processing: D1_GROK_HealthPsycology230-249_39.json
    ✅ Ditambahkan: 39
📄 Processing: D1_GROK_HealthPsycology56-95_70.json
    ✅ Ditambahkan: 70
📄 Processing: D1_GROK_HealthPsycology96-113_36.json
    ✅ Ditambahkan: 36
📄 Processing: D11_GROK_AHandbookfortheSMH105-115_20.json
    ✅ Ditambahkan: 20
📄 Processing: D11_GROK_AHandbookfortheSMH116-126_20.json
    ✅ Ditambahkan: 20
📄 Processing: D11_GROK_AHandbookfortheSMH127-137_20.json
    ✅ Ditambahkan: 20
📄 Processing: D11_GROK_AHandbookfortheSMH138-148_20.json
    ✅ Ditambahkan: 20
📄 Processing: D11_GROK_AHandbookfortheSMH149-159_20.json
    ✅ Ditambahkan: 20
📄 Processing: D11_GROK_AHandbookfortheSMH160-170_20.json
    ✅ Ditambahkan: 20
📄 Processing: D11_GROK_AHandbookfortheSMH17-27_20.json
    ✅ Ditambahkan: 20
📄 Processing: D11_GROK_AHandbookfortheSMH171-181_20.json
    ✅ Ditambahkan: 20
📄 Processing: D11_GROK_AHandbookfortheSMH182-192_20.json
    ✅ Ditambahkan: 20
📄 Processing: D11_GROK_AHandbookfortheSMH193-203_20.json
    ✅ Ditambahkan: 20
📄 Processing: D11_GROK_AHandbookfortheSMH204-214_20.json
    ✅ Ditambahkan: 20
📄 Processing: D11_GROK_AHandbookfortheSMH215-225_20.json
    ✅ Ditambahkan: 20
📄 Processing: D11_GROK_AHandbookfortheSMH226-236_20.json
    ✅ Ditambahkan: 20
📄 Processing: D11_GROK_AHandbookfortheSMH237-247_20.json
    ✅ Ditambahkan: 20
📄 Processing: D11_GROK_AHandbookfortheSMH248-258_20.json
    ✅ Ditambahkan: 20
📄 Processing: D11_GROK_AHandbookfortheSMH259-269_20.json
    ✅ Ditambahkan: 20
📄 Processing: D11_GROK_AHandbookfortheSMH270-280_20.json
    ✅ Ditambahkan: 20
📄 Processing: D11_GROK_AHandbookfortheSMH28-38_20.json
    ✅ Ditambahkan: 20
📄 Processing: D11_GROK_AHandbookfortheSMH281-291_20.json
    ✅ Ditambahkan: 20
📄 Processing: D11_GROK_AHandbookfortheSMH292-302_20.json
    ✅ Ditambahkan: 20
📄 Processing: D11_GROK_AHandbookfortheSMH303-313_20.json
    ✅ Ditambahkan: 20
📄 Processing: D11_GROK_AHandbookfortheSMH314-324_20.json
    ✅ Ditambahkan: 20
📄 Processing: D11_GROK_AHandbookfortheSMH325-335_20.json
    ✅ Ditambahkan: 20
📄 Processing: D11_GROK_AHandbookfortheSMH336-346_20.json
    ✅ Ditambahkan: 20
📄 Processing: D11_GROK_AHandbookfortheSMH347-357_20.json
    ✅ Ditambahkan: 20
📄 Processing: D11_GROK_AHandbookfortheSMH358-368_20.json
    ✅ Ditambahkan: 20
📄 Processing: D11_GROK_AHandbookfortheSMH369-379_20.json
    ✅ Ditambahkan: 20
📄 Processing: D11_GROK_AHandbookfortheSMH380-390_20.json
    ✅ Ditambahkan: 20
📄 Processing: D11_GROK_AHandbookfortheSMH39-49_20.json
    ✅ Ditambahkan: 20
📄 Processing: D11_GROK_AHandbookfortheSMH391-401_20.json
    ✅ Ditambahkan: 20
📄 Processing: D11_GROK_AHandbookfortheSMH402-412_20.json
    ✅ Ditambahkan: 20
📄 Processing: D11_GROK_AHandbookfortheSMH413-423_20.json
    ✅ Ditambahkan: 20
📄 Processing: D11_GROK_AHandbookfortheSMH424-434_20.json
    ✅ Ditambahkan: 20
📄 Processing: D11_GROK_AHandbookfortheSMH435-445_20.json
    ✅ Ditambahkan: 20
📄 Processing: D11_GROK_AHandbookfortheSMH446-456_20.json
    ✅ Ditambahkan: 20
📄 Processing: D11_GROK_AHandbookfortheSMH457-467_20.json
    ✅ Ditambahkan: 20
📄 Processing: D11_GROK_AHandbookfortheSMH468-478_20.json
    ✅ Ditambahkan: 20
📄 Processing: D11_GROK_AHandbookfortheSMH479-489_20.json
    ✅ Ditambahkan: 20
📄 Processing: D11_GROK_AHandbookfortheSMH490-500_20.json
    ✅ Ditambahkan: 20
📄 Processing: D11_GROK_AHandbookfortheSMH50-60_20.json
    ✅ Ditambahkan: 20
📄 Processing: D11_GROK_AHandbookfortheSMH501-511_20.json
    ✅ Ditambahkan: 20
📄 Processing: D11_GROK_AHandbookfortheSMH512-522_20.json
    ✅ Ditambahkan: 20
📄 Processing: D11_GROK_AHandbookfortheSMH523-533_20.json
    ✅ Ditambahkan: 20
📄 Processing: D11_GROK_AHandbookfortheSMH534-544_20.json
    ✅ Ditambahkan: 20
📄 Processing: D11_GROK_AHandbookfortheSMH545-555_20.json
    ✅ Ditambahkan: 20
📄 Processing: D11_GROK_AHandbookfortheSMH556-566_20.json
    ✅ Ditambahkan: 20
📄 Processing: D11_GROK_AHandbookfortheSMH567-577_20.json
    ✅ Ditambahkan: 20
📄 Processing: D11_GROK_AHandbookfortheSMH578-588_20.json
    ✅ Ditambahkan: 20
📄 Processing: D11_GROK_AHandbookfortheSMH589-599_20.json
    ✅ Ditambahkan: 20
📄 Processing: D11_GROK_AHandbookfortheSMH600-609_20.json
    ✅ Ditambahkan: 20
📄 Processing: D11_GROK_AHandbookfortheSMH61-71_20.json
    ✅ Ditambahkan: 20
📄 Processing: D11_GROK_AHandbookfortheSMH72-82_20.json
    ✅ Ditambahkan: 20
📄 Processing: D11_GROK_AHandbookfortheSMH83-93_20.json
    ✅ Ditambahkan: 20
📄 Processing: D11_GROK_AHandbookfortheSMH94-104_20.json
    ✅ Ditambahkan: 20
📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders110-120_20.json
    ✅ Ditambahkan: 20
📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders121-131_20.json
    ✅ Ditambahkan: 20
📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders132-142_20.json
    ✅ Ditambahkan: 20
📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders143-153_20.json
    ✅ Ditambahkan: 20
📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders154-164_20.json
    ✅ Ditambahkan: 20
📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders165-175_20.json
    ✅ Ditambahkan: 20
📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders176-186_20.json
    ✅ Ditambahkan: 20
📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders187-197_20.json
    ✅ Ditambahkan: 20
📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders198-208_20.json
    ✅ Ditambahkan: 20
📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders209-219_20.json
    ✅ Ditambahkan: 20
📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders22-32_20.json
    ✅ Ditambahkan: 20
📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders220-230_20.json
    ✅ Ditambahkan: 20
📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders231-241_20.json
    ✅ Ditambahkan: 20
📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders242-252_20.json
    ✅ Ditambahkan: 20
📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders253-263_20.json
    ✅ Ditambahkan: 20
📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders264-274_20.json
    ✅ Ditambahkan: 20
📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders275-285_20.json
    ✅ Ditambahkan: 20
📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders286-296_20.json
    ✅ Ditambahkan: 20
📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders297-307_20.json
    ✅ Ditambahkan: 20
📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders308-318_20.json
    ✅ Ditambahkan: 20
📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders319-329_20.json
    ✅ Ditambahkan: 20
📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders33-43_20.json
    ✅ Ditambahkan: 20
📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders330-340_20.json
    ✅ Ditambahkan: 20
📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders341-351_20.json
    ✅ Ditambahkan: 20
📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders352-362_20.json
    ✅ Ditambahkan: 20
📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders363-373_20.json
    ✅ Ditambahkan: 20
📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders374-384_20.json
    ✅ Ditambahkan: 20
📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders385-395_20.json
    ✅ Ditambahkan: 20
📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders396-406_20.json
    ✅ Ditambahkan: 20
📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders407-417_20.json
    ✅ Ditambahkan: 20
📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders418-428_20.json
    ✅ Ditambahkan: 20
📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders429-439_20.json
    ✅ Ditambahkan: 20
📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders44-54_20.json
    ✅ Ditambahkan: 20
📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders440-450_20.json
    ✅ Ditambahkan: 20
📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders451-461_20.json
    ✅ Ditambahkan: 20
📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders462-472_20.json
    ✅ Ditambahkan: 20
📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders473-483_20.json
    ✅ Ditambahkan: 20
📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders484-494_20.json
    ✅ Ditambahkan: 20
📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders495-505_20.json
    ✅ Ditambahkan: 20
📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders506-516_20.json
    ✅ Ditambahkan: 20
📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders517-527_20.json
    ✅ Ditambahkan: 20
📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders528-538_20.json
    ✅ Ditambahkan: 20
📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders539-549_20.json
    ✅ Ditambahkan: 20
📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders55-65_20.json
    ✅ Ditambahkan: 20
📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders550-560_20.json
    ✅ Ditambahkan: 20
📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders561-571_20.json
    ✅ Ditambahkan: 20
📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders572-582_20.json
    ✅ Ditambahkan: 20
📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders583-593_20.json
    ✅ Ditambahkan: 20
📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders594-604_20.json
    ✅ Ditambahkan: 20
📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders605-615_20.json
    ✅ Ditambahkan: 20
📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders616-626_20.json
    ✅ Ditambahkan: 20
📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders627-637_20.json
    ✅ Ditambahkan: 20
📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders638-648_20.json
    ✅ Ditambahkan: 20
📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders649-659_20.json
    ✅ Ditambahkan: 20
📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders66-76_20.json
    ✅ Ditambahkan: 20
📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders660-670_20.json
    ✅ Ditambahkan: 20
📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders671-681_20.json
    ✅ Ditambahkan: 20
📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders682-692_20.json
    ✅ Ditambahkan: 20
📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders693-703_20.json
    ✅ Ditambahkan: 20
📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders704-714_20.json
    ✅ Ditambahkan: 20
📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders715-725_20.json
    ✅ Ditambahkan: 20
📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders726-736_20.json
    ✅ Ditambahkan: 20
📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders737-747_20.json
    ✅ Ditambahkan: 20
📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders748-758_20.json
    ✅ Ditambahkan: 20
📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders759-769_20.json
    ✅ Ditambahkan: 20
📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders77-87_20.json
    ✅ Ditambahkan: 20
📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders770-780_20.json
    ✅ Ditambahkan: 20
📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders781-789_20.json
    ✅ Ditambahkan: 20
📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders88-98_20.json
    ✅ Ditambahkan: 20
📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders99-109_20.json
    ✅ Ditambahkan: 20
📄 Processing: D2_GPT_DrAndrewClinicalPsychology44-64_60.json
    ✅ Ditambahkan: 60
📄 Processing: D2_GROK_DrAndrewClinicalPsychology108-130_51.json
    ✅ Ditambahkan: 51
📄 Processing: D2_GROK_DrAndrewClinicalPsychology131-148_48.json
    ✅ Ditambahkan: 48
📄 Processing: D2_GROK_DrAndrewClinicalPsychology150-170_37.json
    ✅ Ditambahkan: 37
📄 Processing: D2_GROK_DrAndrewClinicalPsychology171-194_44.json
    ✅ Ditambahkan: 44
📄 Processing: D2_GROK_DrAndrewClinicalPsychology195-218_35.json
    ✅ Ditambahkan: 35
📄 Processing: D2_GROK_DrAndrewClinicalPsychology219-245_35.json
    ✅ Ditambahkan: 35
📄 Processing: D2_GROK_DrAndrewClinicalPsychology26-43_53.json
    ✅ Ditambahkan: 53
📄 Processing: D2_GROK_DrAndrewClinicalPsychology65-83_51.json
    ✅ Ditambahkan: 51
📄 Processing: D2_GROK_DrAndrewClinicalPsychology84-107_47.json
    ✅ Ditambahkan: 47

==============================
📊 SUMMARY (FOLDER ENG)
Total file JSON diproses       : 144
Total data mentah              : 3443
Total data unik (final)        : 3443
File final disimpan di         : combined_dataset_eng.csv
==============================

In [2]:
import os
import json
import pandas as pd
import csv

# Langsung arahkan ke folder 'idn'
BASE_DIR = r"C:\Users\Liza\Documents\Kerja Praktik 2\dataset\idn"

data = []
total_files = 0
total_items = 0

print(f"📂 Memulai proses di folder: {BASE_DIR}")

if not os.path.exists(BASE_DIR):
    print("❌ Folder tidak ditemukan!")
else:
    for root, dirs, files in os.walk(BASE_DIR):
        for filename in files:
            if not filename.lower().endswith(".json"):
                continue

            file_path = os.path.join(root, filename)
            print(f"📄 Processing: {filename}")
            
            total_files += 1

            # ===== PARSE NAMA FILE =====
            # Mengambil nama lengkap tanpa .json
            source_full_name = filename.replace(".json", "")
            
            parts = source_full_name.split("_")
            if len(parts) >= 2:
                generate_from = parts[1]
                if generate_from.upper() != "GPT":
                    generate_from = "GROK"
            else:
                generate_from = "UNKNOWN"

            # ===== LOAD JSON =====
            try:
                with open(file_path, "r", encoding="utf-8") as f:
                    content = json.load(f)

                if isinstance(content, dict):
                    content = content.get("data", [])

                if not isinstance(content, list):
                    continue

                added_count = 0
                for item in content:
                    question = item.get("Question") or item.get("question") or ""
                    answer = item.get("Answer") or item.get("answer") or ""

                    if question.strip() == "" or answer.strip() == "":
                        continue

                    data.append({
                        "question": question.strip(),
                        "answer": answer.strip(),
                        "from": generate_from,
                        "source": source_full_name, # Nama file lengkap tanpa .json
                        "folder": "idn"
                    })
                    added_count += 1

                total_items += added_count
                print(f"    ✅ Ditambahkan: {added_count}")

            except Exception as e:
                print(f"  ❌ ERROR pada file {filename}: {e}")

# ===== SAVE =====
df = pd.DataFrame(data)

if df.empty:
    print("\n⚠️ Data kosong!")
else:
    # 1. Identifikasi data yang duplikat (untuk pengecekan)
    duplicates = df[df.duplicated(subset=["question", "answer"], keep=False)]

    if not duplicates.empty:
        print(f"\n🔍 Ditemukan {len(duplicates)} baris data duplikat.")
        duplicates_sorted = duplicates.sort_values(by=["question"])
        duplicates_sorted.to_csv("cek_duplikat_idn.csv", index=False, sep=";")
        print(f"📝 Detail duplikat disimpan ke: cek_duplikat_idn.csv")
    else:
        print("\n✅ Tidak ditemukan data duplikat.")

    # 2. PROSES CLEANING (Hapus duplikat)
    df_clean = df.drop_duplicates(subset=["question", "answer"])

    # 3. SAVE HASIL AKHIR
    output_name = "combined_dataset_idn.csv"
    df_clean.to_csv(
        output_name,
        index=False,
        encoding="utf-8",
        sep=";",
        quoting=csv.QUOTE_ALL
    )

    print("\n" + "="*30)
    print("📊 SUMMARY (FOLDER IDN)")
    print(f"Total file JSON diproses       : {total_files}")
    print(f"Total data mentah              : {total_items}")
    print(f"Total data unik (hasil akhir)  : {len(df_clean)}")
    print(f"✅ File final disimpan di       : {output_name}")
    print("="*30)

📂 Memulai proses di folder: C:\Users\Liza\Documents\Kerja Praktik 2\dataset\idn
📄 Processing: D13_GPT_BrainPower101-111_10.json
    ✅ Ditambahkan: 10
📄 Processing: D13_GPT_BrainPower112-122_10.json
    ✅ Ditambahkan: 10
📄 Processing: D13_GPT_BrainPower123-133_27.json
    ✅ Ditambahkan: 27
📄 Processing: D13_GPT_BrainPower13-23_11.json
    ✅ Ditambahkan: 11
📄 Processing: D13_GPT_BrainPower2-12_12.json
    ✅ Ditambahkan: 12
📄 Processing: D13_GPT_BrainPower24-34_11.json
    ✅ Ditambahkan: 11
📄 Processing: D13_GPT_BrainPower35-45_20.json
    ✅ Ditambahkan: 20
📄 Processing: D13_GPT_BrainPower46-56_22.json
    ✅ Ditambahkan: 22
📄 Processing: D13_GPT_BrainPower57-67_19.json
    ✅ Ditambahkan: 19
📄 Processing: D13_GPT_BrainPower68-78_21.json
    ✅ Ditambahkan: 21
📄 Processing: D13_GPT_BrainPower79-89_30.json
    ✅ Ditambahkan: 30
📄 Processing: D13_GPT_BrainPower90-100_10.json
    ✅ Ditambahkan: 10
📄 Processing: D14_GPT_EmotionalFirstAid23-45_50.json
    ✅ Ditambahkan: 50
📄 Processing: D14_GROK_EmotionalFirstAid1-22_41.json
    ✅ Ditambahkan: 41
📄 Processing: D15_GPT_PsikologiKepribadian102-118_46.json
    ✅ Ditambahkan: 46
📄 Processing: D15_GPT_PsikologiKepribadian14-33_50.json
    ✅ Ditambahkan: 50
📄 Processing: D15_GROK_PsikologiKepribadian119-146_57.json
    ✅ Ditambahkan: 57
📄 Processing: D15_GROK_PsikologiKepribadian147-173_52.json
    ✅ Ditambahkan: 52
📄 Processing: D15_GROK_PsikologiKepribadian174-185_25.json
    ✅ Ditambahkan: 25
📄 Processing: D15_GROK_PsikologiKepribadian34-60_47.json
    ✅ Ditambahkan: 47
📄 Processing: D15_GROK_PsikologiKepribadian61-83_99.json
    ✅ Ditambahkan: 99
📄 Processing: D15_GROK_PsikologiKepribadian84-101_46.json
    ✅ Ditambahkan: 46
📄 Processing: D16_GROK_PsikologiKomunikasi117-126_20.json
    ✅ Ditambahkan: 20
📄 Processing: D16_GROK_PsikologiKomunikasi127-137_24.json
    ✅ Ditambahkan: 24
📄 Processing: D16_GROK_PsikologiKomunikasi139-157_59.json
    ✅ Ditambahkan: 59
📄 Processing: D16_GROK_PsikologiKomunikasi17-26_25.json
    ✅ Ditambahkan: 25
📄 Processing: D16_GROK_PsikologiKomunikasi27-33_25.json
    ✅ Ditambahkan: 25
📄 Processing: D16_GROK_PsikologiKomunikasi35-46_25.json
    ✅ Ditambahkan: 25
📄 Processing: D16_GROK_PsikologiKomunikasi47-63_36.json
    ✅ Ditambahkan: 36
📄 Processing: D16_GROK_PsikologiKomunikasi65-74_24.json
    ✅ Ditambahkan: 24
📄 Processing: D16_GROK_PsikologiKomunikasi75-82_25.json
    ✅ Ditambahkan: 25
📄 Processing: D16_GROK_PsikologiKomunikasi83-93_21.json
    ✅ Ditambahkan: 21
📄 Processing: D16_GROK_PsikologiKomunikasi95-116_24.json
    ✅ Ditambahkan: 24
📄 Processing: D17_GROK_DampakGadget1-19_23.json
    ✅ Ditambahkan: 23
📄 Processing: D18_GROK_FilosofiTeras124-148_53.json
    ✅ Ditambahkan: 53
📄 Processing: D18_GROK_FilosofiTeras150-157_26.json
    ✅ Ditambahkan: 26
📄 Processing: D18_GROK_FilosofiTeras159-182_60.json
    ✅ Ditambahkan: 60
📄 Processing: D18_GROK_FilosofiTeras191-227_54.json
    ✅ Ditambahkan: 54
📄 Processing: D18_GROK_FilosofiTeras239-259_37.json
    ✅ Ditambahkan: 37
📄 Processing: D18_GROK_FilosofiTeras261-289_46.json
    ✅ Ditambahkan: 46
📄 Processing: D18_GROK_FilosofiTeras291-303_25.json
    ✅ Ditambahkan: 25
📄 Processing: D18_GROK_FilosofiTeras305-313_25.json
    ✅ Ditambahkan: 25
📄 Processing: D18_GROK_FilosofiTeras31-44_30.json
    ✅ Ditambahkan: 30
📄 Processing: D18_GROK_FilosofiTeras63-89_60.json
    ✅ Ditambahkan: 60
📄 Processing: D18_GROK_FilosofiTeras90-122_61.json
    ✅ Ditambahkan: 61
📄 Processing: D3_GROK_PengantarPsikologiAdnan100-110_20.json
    ✅ Ditambahkan: 20
📄 Processing: D3_GROK_PengantarPsikologiAdnan111-121_20.json
    ✅ Ditambahkan: 20
📄 Processing: D3_GROK_PengantarPsikologiAdnan122-132_20.json
    ✅ Ditambahkan: 20
📄 Processing: D3_GROK_PengantarPsikologiAdnan133-143_20.json
    ✅ Ditambahkan: 20
📄 Processing: D3_GROK_PengantarPsikologiAdnan14-24_20.json
    ✅ Ditambahkan: 20
📄 Processing: D3_GROK_PengantarPsikologiAdnan144-154_20.json
    ✅ Ditambahkan: 20
📄 Processing: D3_GROK_PengantarPsikologiAdnan155-165_20.json
    ✅ Ditambahkan: 20
📄 Processing: D3_GROK_PengantarPsikologiAdnan166-176_20.json
    ✅ Ditambahkan: 20
📄 Processing: D3_GROK_PengantarPsikologiAdnan177-187_20.json
    ✅ Ditambahkan: 20
📄 Processing: D3_GROK_PengantarPsikologiAdnan188-198_20.json
    ✅ Ditambahkan: 20
📄 Processing: D3_GROK_PengantarPsikologiAdnan199-209_20.json
    ✅ Ditambahkan: 20
📄 Processing: D3_GROK_PengantarPsikologiAdnan210-220_20.json
    ✅ Ditambahkan: 20
📄 Processing: D3_GROK_PengantarPsikologiAdnan221-231_20.json
    ✅ Ditambahkan: 20
📄 Processing: D3_GROK_PengantarPsikologiAdnan232-242_20.json
    ✅ Ditambahkan: 20
📄 Processing: D3_GROK_PengantarPsikologiAdnan243-252_20.json
    ✅ Ditambahkan: 20
📄 Processing: D3_GROK_PengantarPsikologiAdnan25-35_20.json
    ✅ Ditambahkan: 20
📄 Processing: D3_GROK_PengantarPsikologiAdnan36-46_20.json
    ✅ Ditambahkan: 20
📄 Processing: D3_GROK_PengantarPsikologiAdnan47-57_20.json
    ✅ Ditambahkan: 20
📄 Processing: D3_GROK_PengantarPsikologiAdnan58-68_20.json
    ✅ Ditambahkan: 20
📄 Processing: D3_GROK_PengantarPsikologiAdnan69-79_20.json
    ✅ Ditambahkan: 20
📄 Processing: D3_GROK_PengantarPsikologiAdnan80-88_20.json
    ✅ Ditambahkan: 20
📄 Processing: D3_GROK_PengantarPsikologiAdnan89-99_20.json
    ✅ Ditambahkan: 20
📄 Processing: D4_GROK_PengantarPsikologiBimoW101-111_20.json
    ✅ Ditambahkan: 20
📄 Processing: D4_GROK_PengantarPsikologiBimoW112-122_20.json
    ✅ Ditambahkan: 20
📄 Processing: D4_GROK_PengantarPsikologiBimoW123-133_20.json
    ✅ Ditambahkan: 20
📄 Processing: D4_GROK_PengantarPsikologiBimoW13-23_20.json
    ✅ Ditambahkan: 20
📄 Processing: D4_GROK_PengantarPsikologiBimoW134-144_20.json
    ✅ Ditambahkan: 20
📄 Processing: D4_GROK_PengantarPsikologiBimoW145-155_20.json
    ✅ Ditambahkan: 20
📄 Processing: D4_GROK_PengantarPsikologiBimoW156-166_20.json
    ✅ Ditambahkan: 20
📄 Processing: D4_GROK_PengantarPsikologiBimoW167-177_20.json
    ✅ Ditambahkan: 20
📄 Processing: D4_GROK_PengantarPsikologiBimoW178-188_20.json
    ✅ Ditambahkan: 20
📄 Processing: D4_GROK_PengantarPsikologiBimoW189-199_20.json
    ✅ Ditambahkan: 20
📄 Processing: D4_GROK_PengantarPsikologiBimoW200-210_20.json
    ✅ Ditambahkan: 20
📄 Processing: D4_GROK_PengantarPsikologiBimoW211-221_20.json
    ✅ Ditambahkan: 20
📄 Processing: D4_GROK_PengantarPsikologiBimoW222-232_20.json
    ✅ Ditambahkan: 20
📄 Processing: D4_GROK_PengantarPsikologiBimoW233-248_22.json
    ✅ Ditambahkan: 22
📄 Processing: D4_GROK_PengantarPsikologiBimoW24-34_20.json
    ✅ Ditambahkan: 20
📄 Processing: D4_GROK_PengantarPsikologiBimoW35-45_20.json
    ✅ Ditambahkan: 20
📄 Processing: D4_GROK_PengantarPsikologiBimoW46-56_20.json
    ✅ Ditambahkan: 20
📄 Processing: D4_GROK_PengantarPsikologiBimoW57-67_20.json
    ✅ Ditambahkan: 20
📄 Processing: D4_GROK_PengantarPsikologiBimoW68-78_20.json
    ✅ Ditambahkan: 20
📄 Processing: D4_GROK_PengantarPsikologiBimoW79-89_20.json
    ✅ Ditambahkan: 20
📄 Processing: D4_GROK_PengantarPsikologiBimoW90-100_20.json
    ✅ Ditambahkan: 20
📄 Processing: D5_GROK_MindfullLife11-20_20.json
    ✅ Ditambahkan: 20
📄 Processing: D5_GROK_MindfullLife21-31_20.json
    ✅ Ditambahkan: 20
📄 Processing: D7_GROK_SeniMenyiksaDiri18-28_15.json
    ✅ Ditambahkan: 15
📄 Processing: D7_GROK_SeniMenyiksaDiri29-42_20.json
    ✅ Ditambahkan: 20
📄 Processing: D7_GROK_SeniMenyiksaDiri43-53_15_15.json
    ✅ Ditambahkan: 15
📄 Processing: D7_GROK_SeniMenyiksaDiri54-67_12.json
    ✅ Ditambahkan: 12
📄 Processing: D7_GROK_SeniMenyiksaDiri68-83_20.json
    ✅ Ditambahkan: 20
📄 Processing: D7_GROK_SeniMenyiksaDiri7-17_20.json
    ✅ Ditambahkan: 20

🔍 Ditemukan 22 baris data duplikat.
📝 Detail duplikat disimpan ke: cek_duplikat_idn.csv

==============================
📊 SUMMARY (FOLDER IDN)
Total file JSON diproses       : 96
Total data mentah              : 2528
Total data unik (hasil akhir)  : 2517
✅ File final disimpan di       : combined_dataset_idn.csv
==============================

In [3]:
import os
import json
import pandas as pd
import csv

BASE_DIR = r"C:\Users\Liza\Documents\Kerja Praktik 2\dataset\idn-ocr"

data = []
total_files = 0
total_items = 0

print(f"📂 Memulai proses di folder: {BASE_DIR}")

if not os.path.exists(BASE_DIR):
    print("❌ Folder tidak ditemukan!")
else:
    for root, dirs, files in os.walk(BASE_DIR):
        for filename in files:
            if not filename.lower().endswith(".json"):
                continue

            file_path = os.path.join(root, filename)
            print(f"📄 Processing: {filename}")
            
            total_files += 1

            # ===== PARSE NAMA FILE =====
            # Mengambil nama lengkap tanpa .json
            source_full_name = filename.replace(".json", "")
            
            parts = source_full_name.split("_")
            if len(parts) >= 2:
                generate_from = parts[1]
                if generate_from.upper() != "GPT":
                    generate_from = "GROK"
            else:
                generate_from = "UNKNOWN"

            # ===== LOAD JSON =====
            try:
                with open(file_path, "r", encoding="utf-8") as f:
                    content = json.load(f)

                if isinstance(content, dict):
                    content = content.get("data", [])

                if not isinstance(content, list):
                    continue

                added_count = 0
                for item in content:
                    question = item.get("Question") or item.get("question") or ""
                    answer = item.get("Answer") or item.get("answer") or ""

                    if question.strip() == "" or answer.strip() == "":
                        continue

                    data.append({
                        "question": question.strip(),
                        "answer": answer.strip(),
                        "from": generate_from,
                        "source": source_full_name, # Nama file lengkap tanpa .json
                        "folder": "idn-ocr"
                    })
                    added_count += 1

                total_items += added_count
                print(f"    ✅ Ditambahkan: {added_count}")

            except Exception as e:
                print(f"  ❌ ERROR pada file {filename}: {e}")

# ===== SAVE =====
df = pd.DataFrame(data)

if df.empty:
    print("\n⚠️ Data kosong!")
else:
    # 1. Identifikasi data yang duplikat (untuk pengecekan)
    duplicates = df[df.duplicated(subset=["question", "answer"], keep=False)]

    if not duplicates.empty:
        print(f"\n🔍 Ditemukan {len(duplicates)} baris data duplikat.")
        duplicates_sorted = duplicates.sort_values(by=["question"])
        duplicates_sorted.to_csv("cek_duplikat_idn-ocr.csv", index=False, sep=";")
        print(f"📝 Detail duplikat disimpan ke: cek_duplikat_idn-ocr.csv")
    else:
        print("\n✅ Tidak ditemukan data duplikat.")

    # 2. PROSES CLEANING (Hapus duplikat)
    df_clean = df.drop_duplicates(subset=["question", "answer"])

    # 3. SAVE HASIL AKHIR
    output_name = "combined_dataset_idn-ocr .csv"
    df_clean.to_csv(
        output_name,
        index=False,
        encoding="utf-8",
        sep=";",
        quoting=csv.QUOTE_ALL
    )

    print("\n" + "="*30)
    print("📊 SUMMARY (FOLDER IDN-OCR)")
    print(f"Total file JSON diproses       : {total_files}")
    print(f"Total data mentah              : {total_items}")
    print(f"Total data unik (hasil akhir)  : {len(df_clean)}")
    print(f"✅ File final disimpan di       : {output_name}")
    print("="*30)

📂 Memulai proses di folder: C:\Users\Liza\Documents\Kerja Praktik 2\dataset\idn-ocr
📄 Processing: D10_GROK_HidupDamaiTanpaBerpikirBerlebihan107-118_20.json
    ✅ Ditambahkan: 20
📄 Processing: D10_GROK_HidupDamaiTanpaBerpikirBerlebihan119-130_20.json
    ✅ Ditambahkan: 20
📄 Processing: D10_GROK_HidupDamaiTanpaBerpikirBerlebihan131-141_20.json
    ✅ Ditambahkan: 20
📄 Processing: D10_GROK_HidupDamaiTanpaBerpikirBerlebihan143-153_20.json
    ✅ Ditambahkan: 20
📄 Processing: D10_GROK_HidupDamaiTanpaBerpikirBerlebihan154-166_20.json
    ✅ Ditambahkan: 20
📄 Processing: D10_GROK_HidupDamaiTanpaBerpikirBerlebihan19-29_20.json
    ✅ Ditambahkan: 20
📄 Processing: D10_GROK_HidupDamaiTanpaBerpikirBerlebihan30-40_20.json
    ✅ Ditambahkan: 20
📄 Processing: D10_GROK_HidupDamaiTanpaBerpikirBerlebihan41-52_20.json
    ✅ Ditambahkan: 20
📄 Processing: D10_GROK_HidupDamaiTanpaBerpikirBerlebihan53-61_20.json
    ✅ Ditambahkan: 20
📄 Processing: D10_GROK_HidupDamaiTanpaBerpikirBerlebihan63-73_20.json
    ✅ Ditambahkan: 20
📄 Processing: D10_GROK_HidupDamaiTanpaBerpikirBerlebihan74-83_20.json
    ✅ Ditambahkan: 20
📄 Processing: D10_GROK_HidupDamaiTanpaBerpikirBerlebihan85-95_20.json
    ✅ Ditambahkan: 20
📄 Processing: D10_GROK_HidupDamaiTanpaBerpikirBerlebihan96-106_20.json
    ✅ Ditambahkan: 20
📄 Processing: D6_GROK_BeraniTidakDisukaiW108-118_10.json
    ✅ Ditambahkan: 10
📄 Processing: D6_GROK_BeraniTidakDisukaiW119-129_15.json
    ✅ Ditambahkan: 15
📄 Processing: D6_GROK_BeraniTidakDisukaiW130-140_14.json
    ✅ Ditambahkan: 14
📄 Processing: D6_GROK_BeraniTidakDisukaiW141-151_12.json
    ✅ Ditambahkan: 12
📄 Processing: D6_GROK_BeraniTidakDisukaiW152-162_10.json
    ✅ Ditambahkan: 10
📄 Processing: D6_GROK_BeraniTidakDisukaiW163-173_13.json
    ✅ Ditambahkan: 13
📄 Processing: D6_GROK_BeraniTidakDisukaiW17-30_25.json
    ✅ Ditambahkan: 25
📄 Processing: D6_GROK_BeraniTidakDisukaiW174-184_12.json
    ✅ Ditambahkan: 12
📄 Processing: D6_GROK_BeraniTidakDisukaiW185-195_10.json
    ✅ Ditambahkan: 10
📄 Processing: D6_GROK_BeraniTidakDisukaiW196-206_15.json
    ✅ Ditambahkan: 15
📄 Processing: D6_GROK_BeraniTidakDisukaiW207-217_10.json
    ✅ Ditambahkan: 10
📄 Processing: D6_GROK_BeraniTidakDisukaiW218-228_15.json
    ✅ Ditambahkan: 15
📄 Processing: D6_GROK_BeraniTidakDisukaiW229-239_14.json
    ✅ Ditambahkan: 14
📄 Processing: D6_GROK_BeraniTidakDisukaiW240-250_15.json
    ✅ Ditambahkan: 15
📄 Processing: D6_GROK_BeraniTidakDisukaiW251-261_15.json
    ✅ Ditambahkan: 15
📄 Processing: D6_GROK_BeraniTidakDisukaiW262-272_15.json
    ✅ Ditambahkan: 15
📄 Processing: D6_GROK_BeraniTidakDisukaiW273-283_15.json
    ✅ Ditambahkan: 15
📄 Processing: D6_GROK_BeraniTidakDisukaiW284-294_15.json
    ✅ Ditambahkan: 15
📄 Processing: D6_GROK_BeraniTidakDisukaiW295-305_15.json
    ✅ Ditambahkan: 15
📄 Processing: D6_GROK_BeraniTidakDisukaiW306-316_15.json
    ✅ Ditambahkan: 15
📄 Processing: D6_GROK_BeraniTidakDisukaiW31-41_14.json
    ✅ Ditambahkan: 14
📄 Processing: D6_GROK_BeraniTidakDisukaiW317-327_15.json
    ✅ Ditambahkan: 15
📄 Processing: D6_GROK_BeraniTidakDisukaiW328-338_10.json
    ✅ Ditambahkan: 10
📄 Processing: D6_GROK_BeraniTidakDisukaiW339-350_15.json
    ✅ Ditambahkan: 15
📄 Processing: D6_GROK_BeraniTidakDisukaiW42-52_15.json
    ✅ Ditambahkan: 15
📄 Processing: D6_GROK_BeraniTidakDisukaiW53-63_15.json
    ✅ Ditambahkan: 15
📄 Processing: D6_GROK_BeraniTidakDisukaiW64-74_10.json
    ✅ Ditambahkan: 10
📄 Processing: D6_GROK_BeraniTidakDisukaiW75-85_10.json
    ✅ Ditambahkan: 10
📄 Processing: D6_GROK_BeraniTidakDisukaiW86-96_15.json
    ✅ Ditambahkan: 15
📄 Processing: D6_GROK_BeraniTidakDisukaiW97-107_15.json
    ✅ Ditambahkan: 15
📄 Processing: D8_GROK_BerdamaiDenganDiriSendiri10-20_20.json
    ✅ Ditambahkan: 20
📄 Processing: D8_GROK_BerdamaiDenganDiriSendiri109-119_20.json
    ✅ Ditambahkan: 20
📄 Processing: D8_GROK_BerdamaiDenganDiriSendiri120-130_20.json
    ✅ Ditambahkan: 20
📄 Processing: D8_GROK_BerdamaiDenganDiriSendiri131-141_20.json
    ✅ Ditambahkan: 20
📄 Processing: D8_GROK_BerdamaiDenganDiriSendiri142-152_20.json
    ✅ Ditambahkan: 20
📄 Processing: D8_GROK_BerdamaiDenganDiriSendiri153-163_20.json
    ✅ Ditambahkan: 20
📄 Processing: D8_GROK_BerdamaiDenganDiriSendiri164-174_20.json
    ✅ Ditambahkan: 20
📄 Processing: D8_GROK_BerdamaiDenganDiriSendiri175-185_20.json
    ✅ Ditambahkan: 20
📄 Processing: D8_GROK_BerdamaiDenganDiriSendiri186-196_20.json
    ✅ Ditambahkan: 20
📄 Processing: D8_GROK_BerdamaiDenganDiriSendiri197-207_20.json
    ✅ Ditambahkan: 20
📄 Processing: D8_GROK_BerdamaiDenganDiriSendiri208-222_20.json
    ✅ Ditambahkan: 20
📄 Processing: D8_GROK_BerdamaiDenganDiriSendiri21-31_15.json
    ✅ Ditambahkan: 15
📄 Processing: D8_GROK_BerdamaiDenganDiriSendiri32-42_20.json
    ✅ Ditambahkan: 20
📄 Processing: D8_GROK_BerdamaiDenganDiriSendiri43-53_20.json
    ✅ Ditambahkan: 20
📄 Processing: D8_GROK_BerdamaiDenganDiriSendiri54-64_20.json
    ✅ Ditambahkan: 20
📄 Processing: D8_GROK_BerdamaiDenganDiriSendiri65-75_20.json
    ✅ Ditambahkan: 20
📄 Processing: D8_GROK_BerdamaiDenganDiriSendiri76-86_20.json
    ✅ Ditambahkan: 20
📄 Processing: D8_GROK_BerdamaiDenganDiriSendiri87-97_20.json
    ✅ Ditambahkan: 20
📄 Processing: D8_GROK_BerdamaiDenganDiriSendiri98-108_20.json
    ✅ Ditambahkan: 20
📄 Processing: D9_GROK_EgoIsTheEnemy106-116_20.json
    ✅ Ditambahkan: 20
📄 Processing: D9_GROK_EgoIsTheEnemy117-127_20.json
    ✅ Ditambahkan: 20
📄 Processing: D9_GROK_EgoIsTheEnemy128-138_20.json
    ✅ Ditambahkan: 20
📄 Processing: D9_GROK_EgoIsTheEnemy139-149_20.json
    ✅ Ditambahkan: 20
📄 Processing: D9_GROK_EgoIsTheEnemy150-160_20.json
    ✅ Ditambahkan: 20
📄 Processing: D9_GROK_EgoIsTheEnemy161-171_20.json
    ✅ Ditambahkan: 20
📄 Processing: D9_GROK_EgoIsTheEnemy172-183_20.json
    ✅ Ditambahkan: 20
📄 Processing: D9_GROK_EgoIsTheEnemy184-194_20.json
    ✅ Ditambahkan: 20
📄 Processing: D9_GROK_EgoIsTheEnemy195-204_20.json
    ✅ Ditambahkan: 20
📄 Processing: D9_GROK_EgoIsTheEnemy205-216_20.json
    ✅ Ditambahkan: 20
📄 Processing: D9_GROK_EgoIsTheEnemy217-227_20.json
    ✅ Ditambahkan: 20
📄 Processing: D9_GROK_EgoIsTheEnemy228-238_20.json
    ✅ Ditambahkan: 20
📄 Processing: D9_GROK_EgoIsTheEnemy239-248_20.json
    ✅ Ditambahkan: 20
📄 Processing: D9_GROK_EgoIsTheEnemy249-259_20.json
    ✅ Ditambahkan: 20
📄 Processing: D9_GROK_EgoIsTheEnemy25-36_20.json
    ✅ Ditambahkan: 20
📄 Processing: D9_GROK_EgoIsTheEnemy260-270_20.json
    ✅ Ditambahkan: 20
📄 Processing: D9_GROK_EgoIsTheEnemy271-282_20.json
    ✅ Ditambahkan: 20
📄 Processing: D9_GROK_EgoIsTheEnemy283-294_20.json
    ✅ Ditambahkan: 20
📄 Processing: D9_GROK_EgoIsTheEnemy39-49_20.json
    ✅ Ditambahkan: 20
📄 Processing: D9_GROK_EgoIsTheEnemy50-60_20.json
    ✅ Ditambahkan: 20
📄 Processing: D9_GROK_EgoIsTheEnemy61-71_20.json
    ✅ Ditambahkan: 20
📄 Processing: D9_GROK_EgoIsTheEnemy72-82_20.json
    ✅ Ditambahkan: 20
📄 Processing: D9_GROK_EgoIsTheEnemy83-93_20.json
    ✅ Ditambahkan: 20
📄 Processing: D9_GROK_EgoIsTheEnemy94-105_20.json
    ✅ Ditambahkan: 20

🔍 Ditemukan 2 baris data duplikat.
📝 Detail duplikat disimpan ke: cek_duplikat_idn-ocr.csv

==============================
📊 SUMMARY (FOLDER IDN-OCR)
Total file JSON diproses       : 86
Total data mentah              : 1529
Total data unik (hasil akhir)  : 1528
✅ File final disimpan di       : combined_dataset_idn-ocr .csv
==============================

## MERGE ALL

In [ ]:
import os
import json
import pandas as pd
import csv

BASE_DIR = r"C:\Users\Liza\Documents\Kerja Praktikm2\dataset"

data = []
total_files = 0
total_items = 0

for subdir in ["eng", "idn", "idn-ocr"]:  # FIX underscore
    main_folder = os.path.join(BASE_DIR, subdir)

    print(f"\n📂 Masuk folder utama: {main_folder}")

    if not os.path.exists(main_folder):
        print("❌ Folder tidak ditemukan!")
        continue

    for root, dirs, files in os.walk(main_folder):
        print(f"\n  📁 Subfolder: {root}")
        print(f"     Jumlah file: {len(files)}")

        for filename in files:
            if not filename.lower().endswith(".json"):
                continue

            file_path = os.path.join(root, filename)
            print(f"    📄 Processing: {filename}")

            total_files += 1

            # ===== PARSE NAMA FILE =====
            name = filename.replace(".json", "")
            parts = name.split("_")

            if len(parts) < 3:
                print("    ⚠️ Skip (nama tidak sesuai):", filename)
                continue

            generate_from = parts[1]
            source = "_".join(parts[2:])

            if generate_from.upper() != "GPT":
                generate_from = "GROK"

            # ===== LOAD JSON =====
            try:
                with open(file_path, "r", encoding="utf-8") as f:
                    content = json.load(f)

                if isinstance(content, dict):
                    content = content.get("data", [])

                if not isinstance(content, list):
                    print("    ❌ Bukan list")
                    continue

                added_count = 0

                for item in content:
                    question = item.get("Question") or item.get("question") or ""
                    answer = item.get("Answer") or item.get("answer") or ""

                    if question.strip() == "" or answer.strip() == "":
                        continue

                    data.append({
                        "question": question.strip(),
                        "answer": answer.strip(),
                        "from": generate_from,   # disamain sama CSV kamu
                        "source": source,
                        "folder": subdir
                    })

                    added_count += 1

                total_items += added_count
                print(f"    ✅ Ditambahkan: {added_count}")

            except Exception as e:
                print(f"    ❌ ERROR: {e}")

# ===== SAVE =====
df = pd.DataFrame(data)

if len(df) == 0:
    print("\n⚠️ Data kosong! Cek lagi struktur JSON.")
else:
    df = df.drop_duplicates(subset=["question", "answer"])
    df = df[df["question"] != ""]
    df = df[df["answer"] != ""]

    df.to_csv(
        "combined_dataset.csv",
        index=False,
        encoding="utf-8",
        sep=";",                 # 🔥 penting
        quoting=csv.QUOTE_ALL    # 🔥 biar aman dari koma & newline
    )

    print("\n======================")
    print("📊 SUMMARY")
    print("Total file diproses:", total_files)
    print("Total data masuk:", len(df))
    print("======================")

📂 Masuk folder utama: C:\Users\Liza\Documents\Kerja Praktik\dataset\eng

  📁 Subfolder: C:\Users\Liza\Documents\Kerja Praktik\dataset\eng
     Jumlah file: 0

  📁 Subfolder: C:\Users\Liza\Documents\Kerja Praktik\dataset\eng\D1-Health Psychology, 9th Ed (Shelley E. Taylor)
     Jumlah file: 10
    📄 Processing: D1_GPT_HealthPsycology152-167_50.json
    ✅ Ditambahkan: 50
    📄 Processing: D1_GPT_HealthPsycology168-183_30.json
    ✅ Ditambahkan: 30
    📄 Processing: D1_GPT_HealthPsycology184-208_50.json
    ✅ Ditambahkan: 50
    📄 Processing: D1_GPT_HealthPsycology209-229_50.json
    ✅ Ditambahkan: 49
    📄 Processing: D1_GPT_HealthPsycology250-268_50.json
    ✅ Ditambahkan: 53
    📄 Processing: D1_GROK_HealthPsycology1-55_67.json
    ✅ Ditambahkan: 67
    📄 Processing: D1_GROK_HealthPsycology114-151_58.json
    ✅ Ditambahkan: 58
    📄 Processing: D1_GROK_HealthPsycology230-249_50.json
    ✅ Ditambahkan: 39
    📄 Processing: D1_GROK_HealthPsycology56-95_67.json
    ✅ Ditambahkan: 70
    📄 Processing: D1_GROK_HealthPsycology96-113_30.json
    ✅ Ditambahkan: 36

  📁 Subfolder: C:\Users\Liza\Documents\Kerja Praktik\dataset\eng\D11-A Handbook for the Study of Mental Health Social
     Jumlah file: 54
    📄 Processing: D11_GROK_AHandbookfortheSMH105-115_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D11_GROK_AHandbookfortheSMH116-126_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D11_GROK_AHandbookfortheSMH127-137_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D11_GROK_AHandbookfortheSMH138-148_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D11_GROK_AHandbookfortheSMH149-159_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D11_GROK_AHandbookfortheSMH160-170_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D11_GROK_AHandbookfortheSMH17-27_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D11_GROK_AHandbookfortheSMH171-181_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D11_GROK_AHandbookfortheSMH182-192_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D11_GROK_AHandbookfortheSMH193-203_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D11_GROK_AHandbookfortheSMH204-214_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D11_GROK_AHandbookfortheSMH215-225_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D11_GROK_AHandbookfortheSMH226-236_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D11_GROK_AHandbookfortheSMH237-247_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D11_GROK_AHandbookfortheSMH248-258_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D11_GROK_AHandbookfortheSMH259-269_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D11_GROK_AHandbookfortheSMH270-280_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D11_GROK_AHandbookfortheSMH28-38_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D11_GROK_AHandbookfortheSMH281-291_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D11_GROK_AHandbookfortheSMH292-302_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D11_GROK_AHandbookfortheSMH303-313_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D11_GROK_AHandbookfortheSMH314-324_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D11_GROK_AHandbookfortheSMH325-335_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D11_GROK_AHandbookfortheSMH336-346_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D11_GROK_AHandbookfortheSMH347-357_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D11_GROK_AHandbookfortheSMH358-368_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D11_GROK_AHandbookfortheSMH369-379_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D11_GROK_AHandbookfortheSMH380-390_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D11_GROK_AHandbookfortheSMH39-49_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D11_GROK_AHandbookfortheSMH391-401_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D11_GROK_AHandbookfortheSMH402-412_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D11_GROK_AHandbookfortheSMH413-423_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D11_GROK_AHandbookfortheSMH424-434_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D11_GROK_AHandbookfortheSMH435-445_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D11_GROK_AHandbookfortheSMH446-456_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D11_GROK_AHandbookfortheSMH457-467_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D11_GROK_AHandbookfortheSMH468-478_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D11_GROK_AHandbookfortheSMH479-489_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D11_GROK_AHandbookfortheSMH490-500_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D11_GROK_AHandbookfortheSMH50-60_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D11_GROK_AHandbookfortheSMH501-511_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D11_GROK_AHandbookfortheSMH512-522_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D11_GROK_AHandbookfortheSMH523-533_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D11_GROK_AHandbookfortheSMH534-544_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D11_GROK_AHandbookfortheSMH545-555_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D11_GROK_AHandbookfortheSMH556-566_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D11_GROK_AHandbookfortheSMH567-577_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D11_GROK_AHandbookfortheSMH578-588_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D11_GROK_AHandbookfortheSMH589-599_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D11_GROK_AHandbookfortheSMH600-609_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D11_GROK_AHandbookfortheSMH61-71_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D11_GROK_AHandbookfortheSMH72-82_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D11_GROK_AHandbookfortheSMH83-93_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D11_GROK_AHandbookfortheSMH94-104_20.json
    ✅ Ditambahkan: 20

  📁 Subfolder: C:\Users\Liza\Documents\Kerja Praktik\dataset\eng\D12-Clinical Handbook Psychological Disorders
     Jumlah file: 70
    📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders110-120_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders121-131_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders132-142_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders143-153_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders154-164_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders165-175_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders176-186_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders187-197_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders198-208_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders209-219_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders22-32_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders220-230_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders231-241_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders242-252_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders253-263_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders264-274_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders275-285_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders286-296_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders297-307_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders308-318_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders319-329_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders33-43_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders330-340_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders341-351_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders352-362_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders363-373_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders374-384_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders385-395_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders396-406_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders407-417_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders418-428_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders429-439_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders44-54_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders440-450_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders451-461_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders462-472_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders473-483_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders484-494_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders495-505_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders506-516_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders517-527_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders528-538_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders539-549_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders55-65_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders550-560_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders561-571_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders572-582_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders583-593_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders594-604_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders605-615_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders616-626_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders627-637_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders638-648_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders649-659_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders66-76_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders660-670_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders671-681_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders682-692_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders693-703_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders704-714_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders715-725_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders726-736_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders737-747_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders748-758_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders759-769_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders77-87_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders770-780_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders781-789_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders88-98_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D12_GROK_ClinicalHandbookPsychologicalDisorders99-109_20.json
    ✅ Ditambahkan: 20

  📁 Subfolder: C:\Users\Liza\Documents\Kerja Praktik\dataset\eng\D2-Dr._Andrew_M._Pomerantz]_Clinical_Psychology
     Jumlah file: 10
    📄 Processing: D2_GPT_DrAndrewClinicalPsychology44-64_60.json
    ✅ Ditambahkan: 60
    📄 Processing: D2_GROK_DrAndrewClinicalPsychology108-130_51.json
    ✅ Ditambahkan: 51
    📄 Processing: D2_GROK_DrAndrewClinicalPsychology131-148_47.json
    ✅ Ditambahkan: 48
    📄 Processing: D2_GROK_DrAndrewClinicalPsychology150-170_38.json
    ✅ Ditambahkan: 37
    📄 Processing: D2_GROK_DrAndrewClinicalPsychology171-194_44.json
    ✅ Ditambahkan: 44
    📄 Processing: D2_GROK_DrAndrewClinicalPsychology195-218_35.json
    ✅ Ditambahkan: 35
    📄 Processing: D2_GROK_DrAndrewClinicalPsychology219-245_35.json
    ✅ Ditambahkan: 35
    📄 Processing: D2_GROK_DrAndrewClinicalPsychology26-43_53.json
    ✅ Ditambahkan: 53
    📄 Processing: D2_GROK_DrAndrewClinicalPsychology65-83_51.json
    ✅ Ditambahkan: 51
    📄 Processing: D2_GROK_DrAndrewClinicalPsychology84-107_47.json
    ✅ Ditambahkan: 47

📂 Masuk folder utama: C:\Users\Liza\Documents\Kerja Praktik\dataset\idn

  📁 Subfolder: C:\Users\Liza\Documents\Kerja Praktik\dataset\idn
     Jumlah file: 0

  📁 Subfolder: C:\Users\Liza\Documents\Kerja Praktik\dataset\idn\D13-Brain Power
     Jumlah file: 12
    📄 Processing: D13_GPT_BrainPower101-111_10.json
    ✅ Ditambahkan: 10
    📄 Processing: D13_GPT_BrainPower112-122_10.json
    ✅ Ditambahkan: 10
    📄 Processing: D13_GPT_BrainPower123-133_27.json
    ✅ Ditambahkan: 27
    📄 Processing: D13_GPT_BrainPower13-23_11.json
    ✅ Ditambahkan: 11
    📄 Processing: D13_GPT_BrainPower2-12_12.json
    ✅ Ditambahkan: 12
    📄 Processing: D13_GPT_BrainPower24-34_11.json
    ✅ Ditambahkan: 11
    📄 Processing: D13_GPT_BrainPower35-45_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D13_GPT_BrainPower46-56_22.json
    ✅ Ditambahkan: 22
    📄 Processing: D13_GPT_BrainPower57-67_19.json
    ✅ Ditambahkan: 19
    📄 Processing: D13_GPT_BrainPower68-78_21.json
    ✅ Ditambahkan: 21
    📄 Processing: D13_GPT_BrainPower79-89_30.json
    ✅ Ditambahkan: 30
    📄 Processing: D13_GPT_BrainPower90-100_10.json
    ✅ Ditambahkan: 10

  📁 Subfolder: C:\Users\Liza\Documents\Kerja Praktik\dataset\idn\D14-EmotionalFirstAid
     Jumlah file: 2
    📄 Processing: D14_GPT_EmotionalFirstAid23-45_50.json
    ✅ Ditambahkan: 50
    📄 Processing: D14_GROK_EmotionalFirstAid1-22_41.json
    ✅ Ditambahkan: 41

  📁 Subfolder: C:\Users\Liza\Documents\Kerja Praktik\dataset\idn\D15-PsikologiKepribadian
     Jumlah file: 8
    📄 Processing: D15_GPT_PsikologiKepribadian102-118_50.json
    ✅ Ditambahkan: 46
    📄 Processing: D15_GPT_PsikologiKepribadian14-33_50.json
    ✅ Ditambahkan: 50
    📄 Processing: D15_GROK_PsikologiKepribadian119-146_57.json
    ✅ Ditambahkan: 57
    📄 Processing: D15_GROK_PsikologiKepribadian147-173_52.json
    ✅ Ditambahkan: 52
    📄 Processing: D15_GROK_PsikologiKepribadian174-185_25.json
    ✅ Ditambahkan: 25
    📄 Processing: D15_GROK_PsikologiKepribadian34-60_47.json
    ✅ Ditambahkan: 47
    📄 Processing: D15_GROK_PsikologiKepribadian61-83_99.json
    ✅ Ditambahkan: 99
    📄 Processing: D15_GROK_PsikologiKepribadian84-101_46.json
    ✅ Ditambahkan: 46

  📁 Subfolder: C:\Users\Liza\Documents\Kerja Praktik\dataset\idn\D16-PsikologiKomunikasi
     Jumlah file: 11
    📄 Processing: D16_GROK_PsikologiKomunikasi117-126_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D16_GROK_PsikologiKomunikasi127-137_24.json
    ✅ Ditambahkan: 24
    📄 Processing: D16_GROK_PsikologiKomunikasi139-157_59.json
    ✅ Ditambahkan: 59
    📄 Processing: D16_GROK_PsikologiKomunikasi17-26_25.json
    ✅ Ditambahkan: 25
    📄 Processing: D16_GROK_PsikologiKomunikasi27-33_25.json
    ✅ Ditambahkan: 25
    📄 Processing: D16_GROK_PsikologiKomunikasi35-46_25.json
    ✅ Ditambahkan: 25
    📄 Processing: D16_GROK_PsikologiKomunikasi47-63_36.json
    ✅ Ditambahkan: 36
    📄 Processing: D16_GROK_PsikologiKomunikasi65-74_24.json
    ✅ Ditambahkan: 24
    📄 Processing: D16_GROK_PsikologiKomunikasi75-82_25.json
    ✅ Ditambahkan: 25
    📄 Processing: D16_GROK_PsikologiKomunikasi83-93_21.json
    ✅ Ditambahkan: 21
    📄 Processing: D16_GROK_PsikologiKomunikasi95-116_24.json
    ✅ Ditambahkan: 24

  📁 Subfolder: C:\Users\Liza\Documents\Kerja Praktik\dataset\idn\D17-Dampak Gadget
     Jumlah file: 1
    📄 Processing: D17_GROK_DampakGadget1-19_23.json
    ✅ Ditambahkan: 23

  📁 Subfolder: C:\Users\Liza\Documents\Kerja Praktik\dataset\idn\D18-FilosofiTeras
     Jumlah file: 11
    📄 Processing: D18_GROK_FilosofiTeras124-148_53.json
    ✅ Ditambahkan: 53
    📄 Processing: D18_GROK_FilosofiTeras150-157_26.json
    ✅ Ditambahkan: 26
    📄 Processing: D18_GROK_FilosofiTeras159-182_60.json
    ✅ Ditambahkan: 60
    📄 Processing: D18_GROK_FilosofiTeras191-227_54.json
    ✅ Ditambahkan: 54
    📄 Processing: D18_GROK_FilosofiTeras239-259_37.json
    ✅ Ditambahkan: 37
    📄 Processing: D18_GROK_FilosofiTeras261-289_46.json
    ✅ Ditambahkan: 46
    📄 Processing: D18_GROK_FilosofiTeras291-303_25.json
    ✅ Ditambahkan: 25
    📄 Processing: D18_GROK_FilosofiTeras305-313_25.json
    ✅ Ditambahkan: 25
    📄 Processing: D18_GROK_FilosofiTeras31-44_30.json
    ✅ Ditambahkan: 30
    📄 Processing: D18_GROK_FilosofiTeras63-89_60.json
    ✅ Ditambahkan: 60
    📄 Processing: D18_GROK_FilosofiTeras90-122_61.json
    ✅ Ditambahkan: 61

  📁 Subfolder: C:\Users\Liza\Documents\Kerja Praktik\dataset\idn\D3-Pengantar Psikologi (Adnan Achiruddin Saleh) (Z-Library)
     Jumlah file: 22
    📄 Processing: D3_GROK_PengantarPsikologiAdnan100-110_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D3_GROK_PengantarPsikologiAdnan111-121_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D3_GROK_PengantarPsikologiAdnan122-132_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D3_GROK_PengantarPsikologiAdnan133-143_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D3_GROK_PengantarPsikologiAdnan14-24_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D3_GROK_PengantarPsikologiAdnan144-154_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D3_GROK_PengantarPsikologiAdnan155-165_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D3_GROK_PengantarPsikologiAdnan166-176_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D3_GROK_PengantarPsikologiAdnan177-187_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D3_GROK_PengantarPsikologiAdnan188-198_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D3_GROK_PengantarPsikologiAdnan199-209_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D3_GROK_PengantarPsikologiAdnan210-220_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D3_GROK_PengantarPsikologiAdnan221-231_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D3_GROK_PengantarPsikologiAdnan232-242_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D3_GROK_PengantarPsikologiAdnan243-252_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D3_GROK_PengantarPsikologiAdnan25-35_20.json
    ✅ Ditambahkan: 20
    📄 Processing: D3_GROK_PengantarPsikologiAdnan36-46_20.json
    ✅ Ditambahkan: 20

In [5]:
import os
print(os.getcwd())

c:\Users\Liza\Documents\Kerja Praktik\dataset

In [28]:
df1 = pd.read_csv("combined_dataset.csv", sep=";")  # PENTING: sesuaikan separator
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7488 entries, 0 to 7487
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   question  7488 non-null   object
 1   answer    7488 non-null   object
 2   from      7488 non-null   object
 3   source    7488 non-null   object
 4   folder    7488 non-null   object
dtypes: object(5)
memory usage: 292.6+ KB

In [47]:
df2 = pd.read_csv(
    r"upload\dataset-QnA_7500.csv",
    sep=";",              # <-- ini kunci
    quotechar='"',        # handle kutip
    engine="python"       # lebih aman untuk teks panjang
)

df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7500 entries, 0 to 7499
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   question  7500 non-null   object
 1   answer    7500 non-null   object
 2   from      7500 non-null   object
dtypes: object(3)
memory usage: 175.9+ KB

In [42]:
df2 = pd.read_csv(
    r"bertopic_results(5).csv",
    sep=";",              # <-- ini kunci
    quotechar='"',        # handle kutip
    engine="python"       # lebih aman untuk teks panjang
)

df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7500 entries, 0 to 7499
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   question               7500 non-null   object
 1   answer                 7500 non-null   object
 2   from                   7500 non-null   object
 3   filename               7500 non-null   object
 4   document_preprocessed  7500 non-null   object
 5   Topic                  7500 non-null   int64
 6   Probability            7500 non-null   float64
 7   Top_n_words            7500 non-null   object
 8   Name                   7500 non-null   object
 9   Document               7500 non-null   object
dtypes: float64(1), int64(1), object(8)
memory usage: 586.1+ KB

In [43]:
df1["key"] = df1["question"].str.strip() + "||" + df1["answer"].str.strip()
df2["key"] = df2["question"].str.strip() + "||" + df2["answer"].str.strip()

In [44]:
missing = df2[~df2["key"].isin(df1["key"])]
print("Jumlah missing:", len(missing))

Jumlah missing: 0

In [48]:
dup = df2[df2.duplicated(subset=["question", "answer"], keep=False)]

print("Jumlah baris duplicate:", len(dup))
print("Jumlah pasangan unik duplicate:", dup.drop_duplicates(subset=["question", "answer"]).shape[0])

Jumlah baris duplicate: 24
Jumlah pasangan unik duplicate: 12

In [49]:
dup_unique = dup.drop_duplicates(subset=["question", "answer"])

dup_unique[["question", "answer"]].head(12)

,question,answer
219,Aku takut dikira nggak pinter karena nilaiku j...,"Nilai jelek bisa bikin ragu, ya. Tapi coba fok..."
220,Aku marah karena tetangga parkir sembarangan. ...,"Parkir sembarangan emang bikin kesel, ya. Coba..."
221,Aku sedih karena nggak di-like postinganku. Ra...,"Nggak di-like bisa bikin sedih, ya. Tapi coba ..."
222,Aku kesal karena temen bilang aku nggak asik. ...,"Komentar temen bisa bikin nggak enak, ya. Tapi..."
629,"Aku stres gara-gara kena keseleo, rasanya susa...","Keseleo bisa bikin frustrasi, tapi coba lihat ..."
634,"Aku sedih gara-gara jaketku rusak, rasanya nye...","Jaket rusak bisa bikin bete, tapi coba bayangi..."
637,"Aku nyesel banget pernah nyakitin orang tua, s...","Nyesel sama masa lalu bisa bikin berat, tapi t..."
640,"Aku suka ngeluh kalau kerjaan telat selesai, b...",Kerjaan telat selesai bisa bikin pengen ngeluh...
642,Aku ngerasa kurang gara-gara nggak punya libur...,"Pengen liburan mewah bisa bikin merasa kurang,..."
696,Aku ngerasa temenku cuma deket kalau aku punya...,Temen yang cuma deket pas ada waktu bisa bikin...
926,Saya sering bilang ke anak bahwa sekolah mahal...,"Aku tahu, kadang kita pengin anak ngerti pengo..."
6516,"Aku merasa pendiam dan nggak menarik, makanya ...","Nggak ada yang salah dengan sifat pendiam, itu..."

In [41]:
dup_detail = (
    df2.groupby(["question", "answer"])
    .size()
    .reset_index(name="count")
    .sort_values(by="count", ascending=False)
)

dup_detail[dup_detail["count"] > 1]

,question,answer,count
647,Aku marah karena tetangga parkir sembarangan. ...,"Parkir sembarangan emang bikin kesel, ya. Coba...",2
4209,"Aku stres gara-gara kena keseleo, rasanya susa...","Keseleo bisa bikin frustrasi, tapi coba lihat ...",2
4847,Aku takut dikira nggak pinter karena nilaiku j...,"Nilai jelek bisa bikin ragu, ya. Tapi coba fok...",2
567,Aku kesal karena temen bilang aku nggak asik. ...,"Komentar temen bisa bikin nggak enak, ya. Tapi...",2
3607,"Aku sedih gara-gara jaketku rusak, rasanya nye...","Jaket rusak bisa bikin bete, tapi coba bayangi...",2
4427,"Aku suka ngeluh kalau kerjaan telat selesai, b...",Kerjaan telat selesai bisa bikin pengen ngeluh...,2
2792,"Aku nyesel banget pernah nyakitin orang tua, s...","Nyesel sama masa lalu bisa bikin berat, tapi t...",2
2217,Aku ngerasa kurang gara-gara nggak punya libur...,"Pengen liburan mewah bisa bikin merasa kurang,...",2
3619,Aku sedih karena nggak di-like postinganku. Ra...,"Nggak di-like bisa bikin sedih, ya. Tapi coba ...",2
7189,Saya sering bilang ke anak bahwa sekolah mahal...,"Aku tahu, kadang kita pengin anak ngerti pengo...",2
1639,"Aku merasa pendiam dan nggak menarik, makanya ...","Nggak ada yang salah dengan sifat pendiam, itu...",2
2566,Aku ngerasa temenku cuma deket kalau aku punya...,Temen yang cuma deket pas ada waktu bisa bikin...,2

In [1]:
import json
import os
import pandas as pd

FILE_PATH = "idn-ocr\D10-Hidup Damai Tanpa Berpikir Berlebihan\D10_GROK_HidupDamaiTanpaBerpikirBerlebihan19-29_20.json"  # <-- ganti ini

# ===== PARSE NAMA FILE =====
filename = os.path.basename(FILE_PATH)
name = filename.replace(".json", "")
parts = name.split("_")

generate_from = parts[1]
source = "_".join(parts[2:])

if generate_from.upper() != "GPT":
    generate_from = "GROK"

# ===== LOAD JSON =====
with open(FILE_PATH, "r", encoding="utf-8") as f:
    content = json.load(f)

data = []

for item in content:
    data.append({
        "Question": item.get("Question", "").strip(),
        "Answer": item.get("Answer", "").strip(),
        "Source": source,
        "Generate From": generate_from
    })

df = pd.DataFrame(data)

# ===== LIHAT HASIL =====
print("Jumlah data:", len(df))
print(df.head(5))

# Optional save
df.to_csv("test_output.csv", index=False, encoding="utf-8")

<>:5: SyntaxWarning: invalid escape sequence '\D'
<>:5: SyntaxWarning: invalid escape sequence '\D'
C:\Users\Liza\AppData\Local\Temp\ipykernel_16680\1938512996.py:5: SyntaxWarning: invalid escape sequence '\D'
  FILE_PATH = "idn-ocr\D10-Hidup Damai Tanpa Berpikir Berlebihan\D10_GROK_HidupDamaiTanpaBerpikirBerlebihan19-29_20.json"  # <-- ganti ini

Jumlah data: 20
                                            Question  \
0  Aku merasa bingung, sebenarnya untuk apa sih k...
1  Kadang aku merasa kerja cuma buat uang, apa it...
2  Aku merasa sia-sia kerja keras, nggak dihargai...
3  Aku pengen kerja yang bikin aku berkembang, ta...
4  Aku capek banget kerja, rasanya cuma buat oran...

                                              Answer  \
0  Wah, pertanyaan yang dalam, ya. Kalau dipikir-...
1  Nggak salah sama sekali! Bekerja buat uang itu...
2  Aduh, pasti nggak enak banget rasanya. Kalau m...
3  Nggak ada yang salah dengan keinginanmu! Ingin...
4  Wah, kedengerannya kamu lagi kelelahan, ya. Ka...

                                      Source Generate From
0  HidupDamaiTanpaBerpikirBerlebihan19-29_20          GROK
1  HidupDamaiTanpaBerpikirBerlebihan19-29_20          GROK
2  HidupDamaiTanpaBerpikirBerlebihan19-29_20          GROK
3  HidupDamaiTanpaBerpikirBerlebihan19-29_20          GROK
4  HidupDamaiTanpaBerpikirBerlebihan19-29_20          GROK

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Question       20 non-null     object
 1   Answer         20 non-null     object
 2   Source         20 non-null     object
 3   Generate From  20 non-null     object
dtypes: object(4)
memory usage: 772.0+ bytes